// src/app/presentation.component.ts
import { Component } from '@angular/core';
import { OnInit } from '@angular/core'

import { PresentationService } from './presentation.service'

@Component({
  selector: '[presentation]',
  templateUrl: 'presentation.component.html',
  providers: [ PresentationService ]
})

export class PresentationComponent implements OnInit {
  internationalOral: string[];
  domesticOral: string[];
  domesticPoster: string[];
  summerSchool: string[];

  constructor (private presentationService: PresentationService) {}

  ngOnInit() {
    this.presentationService.getPresentations()
      .subscribe(res => {
        this.domesticOral = res
          .filter(p => p['style'] == 'oral' && p['officialLang'] == 'ja')
          .sort(this.sortedByDateDesc);
        this.domesticPoster = res
          .filter(p => p['style'] == 'poster')
          .sort(this.sortedByDateDesc);
        this.summerSchool = res
          .filter(p => p['style'] == 'summerSchool')
          .sort(this.sortedByDateDesc);
        this.internationalOral = res
          .filter(p => p['style'] == 'oral' && p['officialLang'] == 'en')
          .sort(this.sortedByDateDesc)
      })
  }

  private sortedByDateDesc(a, b) {
    let parsedDateA = Date.parse(a['date']['from']);
    let parsedDateB = Date.parse(b['date']['from']);
    if (parsedDateA < parsedDateB) {
      return 1;
    }
    if (parsedDateA > parsedDateB) {
      return -1;
    }
    return 1;
  }
}


<h2>
  <a href="#presentation">
    <i class="fa fa-bar-chart"></i>Presentation
  </a>
</h2>
<ul class="fa-ul">
  <li><i class="fa-li fa fa-university"></i>International (Oral)
    <ol reversed="reversed">
      <li *ngFor="let p of internationalOral">
        <presentation-detail [p]="p"></presentation-detail>
      </li>
    </ol>
  </li>
  <li><i class="fa-li fa fa-university"></i>Domestic (Oral)
    <ol reversed="reversed">
      <li *ngFor="let p of domesticOral">
        <presentation-detail [p]="p"></presentation-detail>
      </li>
    </ol>
  </li>
  <li><i class="fa-li fa fa-university"></i>Domestic (Poster)
    <ol reversed="reversed">
      <li *ngFor="let p of domesticPoster">
        <presentation-detail [p]="p"></presentation-detail>
      </li>
    </ol>
  </li>
  <li><i class="fa-li fa fa-university"></i>Summer School
    <ol reversed="reversed">
      <li *ngFor="let p of summerSchool">
        <presentation-detail [p]="p"></presentation-detail>
      </li>
    </ol>
  </li>
</ul>

// src/Presentation.tsx
import React from 'react';
import { FormattedMessage } from 'react-intl';
import PresentationDetail from './PresentationDetail';
import { presentations } from './data/presentations';
import { Presentation as PresentationType } from './types/presentation';

const sortedByDateDesc = (a: PresentationType, b: PresentationType) => {
  const split_a = a.date.from.split(/[^0-9]/).map(Number);
  const split_b = b.date.from.split(/[^0-9]/).map(Number);
  const parsedDateA = new Date(split_a[0], split_a[1] - 1, split_a[2]);
  const parsedDateB = new Date(split_b[0], split_b[1] - 1, split_b[2]);
  return parsedDateB.getTime() - parsedDateA.getTime();
};

const Presentation = () => {
  const categorizedPresentations = {
    domesticOral: presentations
      .filter((p) => p.style === 'oral' && p.officialLang === 'ja')
      .sort(sortedByDateDesc),
    domesticPoster: presentations
      .filter((p) => p.style === 'poster' && p.officialLang === 'ja')
      .sort(sortedByDateDesc),
    summerSchool: presentations
      .filter((p) => p.style === 'summerSchool')
      .sort(sortedByDateDesc),
    internationalOral: presentations
      .filter((p) => p.style === 'oral' && p.officialLang === 'en')
      .sort(sortedByDateDesc),
    internationalPoster: presentations
      .filter((p) => p.style === 'poster' && p.officialLang === 'en')
      .sort(sortedByDateDesc),
    seminar: presentations
      .filter((p) => p.style === 'seminar')
      .sort(sortedByDateDesc),
  };

  return (
    <section id="presentation" className="main">
      <h2>
        <a href="/presentation">
          <i className="fa fa-bar-chart" />
          <FormattedMessage id="presentation" />
        </a>
      </h2>
      <ul className="fa-ul">
        <li>
          <i className="fa-li fa fa-university" />
          <FormattedMessage id="international.oral" />
          <ol reversed>
            <PresentationDetail presentations={categorizedPresentations.internationalOral} />
          </ol>
        </li>
        <li>
          <i className="fa-li fa fa-university" />
          <FormattedMessage id="international.poster" />
          <ol reversed>
            <PresentationDetail presentations={categorizedPresentations.internationalPoster} />
          </ol>
        </li>
        <li>
          <i className="fa-li fa fa-university" />
          <FormattedMessage id="domestic.oral" />
          <ol reversed>
            <PresentationDetail presentations={categorizedPresentations.domesticOral} />
          </ol>
        </li>
        <li>
          <i className="fa-li fa fa-university" />
          <FormattedMessage id="domestic.poster" />
          <ol reversed>
            <PresentationDetail presentations={categorizedPresentations.domesticPoster} />
          </ol>
        </li>
        <li>
          <i className="fa-li fa fa-university" />
          <FormattedMessage id="summer.school" />
          <ol reversed>
            <PresentationDetail presentations={categorizedPresentations.summerSchool} />
          </ol>
        </li>
        <li>
          <i className="fa-li fa fa-university" />
          <FormattedMessage id="seminar" />
          <ol reversed>
            <PresentationDetail presentations={categorizedPresentations.seminar} />
          </ol>
        </li>
      </ul>
    </section>
  );
};

export default Presentation;
